### ISSUE TITLE
Reloading a page with a redirect-response in the URL does not trigger the handler

### ISSUE THREAD

**Issue by sisou** [nimiq/rpc#4]
When reloading a URL with a RPC redirect response in it, the registered handler for that response does not get called, because the `_waitingRequest` is already removed from the `SessionStorage`, so the RPC response gets ignored as `unkown response`.

**Comment by Bettelstab** [comment]
I guess this is solved, isn't it @sisou ?

**Comment by sisou** [comment]
It's only solved in the soeren/url-encoded-popups branch, which is not merged yet.
